-- ==============================================================================
-- AURA MUSIC PLAYER — SUPABASE BACKEND SCHEMA
-- ==============================================================================
-- Run this in your Supabase SQL Editor (https://app.supabase.com/project/_/sql)

-- 1. Create Tracks Table
create table if not exists public.tracks (
    id text primary key,
    title text not null,
    artist text not null,
    album text default 'Single',
    duration integer default 180,
    cover_url text,
    audio_url text not null,
    bitrate text default '320kbps Original',
    format text default 'MP3',
    type text default 'music',
    lyrics text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Playlists Table
create table if not exists public.playlists (
    id text primary key,
    name text not null,
    description text default '',
    cover_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Playlist Tracks Junction
create table if not exists public.playlist_tracks (
    id bigint generated by default as identity primary key,
    playlist_id text references public.playlists(id) on delete cascade not null,
    track_id text references public.tracks(id) on delete cascade not null,
    position integer default 0,
    added_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(playlist_id, track_id)
);

-- 4. Create Favorites / Likes Table
create table if not exists public.likes (
    track_id text references public.tracks(id) on delete cascade primary key,
    liked_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Create Storage Bucket for Audio & Cover Files
insert into storage.buckets (id, name, public)
values ('audio-files', 'audio-files', true)
on conflict (id) do nothing;

-- 6. Enable Row Level Security (RLS) with Public Anon Access
alter table public.tracks enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_tracks enable row level security;
alter table public.likes enable row level security;

-- Policies for Tracks (Allow Read & Write with Anon Key)
create policy "Allow public read access on tracks"
on public.tracks for select using (true);

create policy "Allow public insert on tracks"
on public.tracks for insert with check (true);

create policy "Allow public update on tracks"
on public.tracks for update using (true);

create policy "Allow public delete on tracks"
on public.tracks for delete using (true);

-- Policies for Playlists
create policy "Allow public read on playlists"
on public.playlists for select using (true);

create policy "Allow public insert on playlists"
on public.playlists for insert with check (true);

create policy "Allow public update on playlists"
on public.playlists for update using (true);

create policy "Allow public delete on playlists"
on public.playlists for delete using (true);

-- Policies for Playlist Tracks
create policy "Allow public read on playlist_tracks"
on public.playlist_tracks for select using (true);

create policy "Allow public insert on playlist_tracks"
on public.playlist_tracks for insert with check (true);

create policy "Allow public delete on playlist_tracks"
on public.playlist_tracks for delete using (true);

-- Policies for Likes
create policy "Allow public read on likes"
on public.likes for select using (true);

create policy "Allow public insert on likes"
on public.likes for insert with check (true);

create policy "Allow public delete on likes"
on public.likes for delete using (true);

-- Policies for Storage Bucket Objects
create policy "Allow public read of audio files"
on storage.objects for select
using (bucket_id = 'audio-files');

create policy "Allow public upload to audio files"
on storage.objects for insert
with check (bucket_id = 'audio-files');

create policy "Allow public update to audio files"
on storage.objects for update
using (bucket_id = 'audio-files');

create policy "Allow public delete of audio files"
on storage.objects for delete
using (bucket_id = 'audio-files');
